### ISSUE TITLE
Totem triggering in end causing server crash

### ISSUE THREAD

**Issue by campbebj** [Tacodude7729/Totemic-Overhaul-Fabric#8]
Ive got a netherite active totem with "Death Save" and "Spawn Teleport" and if i die in the end then it crashes the server. 

when the server restarts i end up standing in the middle of the void in the end with half  heart and no durability damage on the totem.

**Comment by Tacodude7729** [comment]
Unable to reproduce. Crash log?

**Comment by campbebj** [comment]
You tested on a server and not on single player right? 

```
[14:57:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bon000$modifiedRunLoop(MinecraftServer.java:10810) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.class_3218.method_18774(class_3218.java:942) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.redirect$bpj000$crashRemovePlayer(class_3218.java:8565) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18770(class_3218.java:958) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14251(class_3222.java:1440) ~[intermediary-server.jar:?]
        at net.fabricmc.totemicoverhaul.effects.TotemEffectSpawnTP.applyActive(TotemEffectSpawnTP.java:115) ~[totemic-overhaul-1.1.3.jar:?]
        at net.fabricmc.totemicoverhaul.TotemItem.activateTotem(TotemItem.java:184) ~[totemic-overhaul-1.1.3.jar:?]
        at net.minecraft.class_1309.redirect$ble000$tryUseTotem(class_1309.java:10329) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1101) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[intermediary-server.jar:?]
        at net.minecraft.class_1678.method_7454(class_1678.java:311) ~[intermediary-server.jar:?]
        at net.minecraft.class_1676.method_7488(class_1676.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.class_1678.method_7488(class_1678.java:329) ~[intermediary-server.jar:?]
        at net.minecraft.class_1678.method_5773(class_1678.java:244) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$bfa000$ficUpdateSuppressionCrashTick(MinecraftServer.java:6707) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
        ... 6 more
```1
